#!/bin/bash

# cd to app root
CWD=$(dirname $0)
if [[ `basename $(pwd)` = 'scripts' ]]; then
  cd ../
else
  cd `dirname $CWD`
fi

echo "Building Image..." && \
docker build -t rancher/bpg:latest . && \
echo "Pushing Image..." && \
docker push rancher/bpg:latest && \
echo "OK"
